#!/bin/bash

# mkdeployment 
# turn the current repo into a production deployment
# note: this removes the .git directories, effectively de-gitting the
# directory.

set -u
umask 0022

# make sure this is what we want.
CONFIRM=''
CONFIRMCOUNT=3
while [[ ${CONFIRM} != 'y' && ${CONFIRM} != 'Y' ]]; do
  echo "This will remove the .git directories and merge customizations." 1>&2
  echo "It CANNOT BE UNDONE, you will need to re-clone the repo." 1>&2
  printf "%s" "Proceed with destructive operation? <y/n>: " 1>&2
  read CONFIRM
  if [[ ${CONFIRM} == 'n' || ${CONFIRM} == 'N' ]]; then
    echo "Aborted!" 1>&2
    exit 1
  fi
  CONFIRMCOUNT=$(( ${CONFIRMCOUNT} - 1 ))
  if [[ ${CONFIRMCOUNT} -le 1 ]]; then
    echo "Aborted! Too many invalid responses." 1>&2
    exit 1
  fi
done


# do stuff



